language: go
branches:
  only:
  - master
before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
  - go test -benchmem -bench .
notifications:
  email: false
